### ISSUE TITLE
How can I compile/run on windows?

### ISSUE THREAD

**Issue by jetstrike** [autoreleasefool/fourteenth-clue#1]
I am not familiar with Swift at all. I tried a couple different tools but I couldn't ever get it to compile.

**Comment by autoreleasefool** [comment]
I'm actually not sure, I don't have any windows machine available to test on. You won't be able to build the iOS app (building for iOS is only supported on macOS), but you might be able to run the CLI app.

If you can get Swift itself working with the [Getting started](https://www.swift.org/getting-started/) instructions, then it should be as simple as `swift run` in the repo directory to build and run the CLI app. I don't have a windows machine to test with, so I can't offer much support, sorry!

I'm going to close this issue as won't fix, but we can continue discussing here if you need.
